#!/usr/bin/env python

import sys
import string
from collections import Counter
import argparse
import time

parser=argparse.ArgumentParser()
parser.add_argument('fname', type=str, help='Input file name')

args = parser.parse_args()
fname = args.fname

with open(fname) as f:
    data = f.read()

data_without_punctuation = data.translate(None, string.punctuation)
data_without_newlines = ' '.join(data_without_punctuation.split('\n'))
data_without_newlines = data_without_newlines.lower()
data_as_string_list = data_without_newlines.split(' ')

c = Counter(data_as_string_list)
word_freqs = c.most_common()

time.sleep(10)

for word, count in word_freqs:
    print("{} {}".format(count, word))
